CREATE TABLE if not EXISTS animals (
  animal_name CHARACTER VARYING(20) NOT NULL,
  animal_breed CHARACTER VARYING(20),
  animal_species CHARACTER VARYING(20) NOT NULL,
  animal_description CHARACTER VARYING(20) NOT NULL,
  animalid INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL
);
